### ISSUE TITLE
Access Violation in native-tls-hook.js during Frida Script Execution

### ISSUE THREAD

**Issue by ItsMarcoDE** [httptoolkit/frida-android-unpinning#121]
**Description:**
An access violation error occurs when running Frida scripts using the `native-tls-hook.js` file, causing the application to crash. The issue arises after repeated attempts to hook the `ssl_verify_peer_cert` function.  

**Expected Behavior:**
The script should run without crashes and successfully perform the intended hooking functionality.  

**Actual Behavior:**
The application crashes with a null pointer dereference (Access Violation) error.  

**Log Excerpt:**
```plaintext
Error: access violation accessing 0x0
    at <anonymous> (/Users/marco/Documents/Android/frida-scripte/native-tls-hook.js:111)
```

**System Information:**
- **Device:** Pixel 8
- **Android Version:** 15 (AP3A.241105.007/12470370)
- **Frida Version:** 16.5.7
- **Script:** `native-tls-hook.js`

**Attachments:**
- Full log output
[log.txt](https://github.com/user-attachments/files/17868458/log.txt)

**Comment by pimterry** [comment]
Is it possible to share which app is triggering this, and steps to reproduce the issue? From the logs it looks like there are some other scripts involved too, it would be helpful to check it's possible to hit this issue when using only this one script.

Null pointers in the native-tls-hook have previously been an issue in concurrent scenarios, but the idea was that https://github.com/httptoolkit/frida-interception-and-unpinning/commit/5b0fd454b9df014c51b3c9c119f7086233ac4f12 should have fixed this. I assume you are using the latest version of that script?

It'd be helpful to add some logging and check exactly which line is failing and where the null pointer is coming from in this scenario.
