### ISSUE TITLE
com.cw.fullepisodes.android

### ISSUE THREAD

**Issue by 89z** [httptoolkit/frida-android-unpinning#15]
I tried using this app with:

- Just Frida
- Frida + user certificate
- Frida + system certificate

but during the ad before the video, you get this:

~~~
Error
You have encountered an error
GO BACK
~~~

**Comment by pimterry** [comment]
To be clear, the app does work correctly on this device when run without using Frida at all? Just to confirm that this is a Frida detection issue, not a general root detection issue.

Anything in the ADB logcat output that provides more detail on the error?

**Comment by 89z** [comment]
Sorry for the spam. Yes I did remember to check this time that it works without Frida/proxy. I was able to bypass the problem, by letting the program start without proxy, then killing it with "Force stop", then starting it again with proxy. Normally this might be a problem if you need to catch the initial requests on app start, but I believe you can capture those as well by just starting app with proxy going. So it seems you can capture all requests, you just need to use a different method to capture the video requests. I will close this for now, thanks!
