### ISSUE TITLE
Facebook

### ISSUE THREAD

**Issue by 89z** [httptoolkit/frida-android-unpinning#18]
I see you mention Facebook here:

https://httptoolkit.tech/blog/frida-certificate-pinning/#caveats

but I think its a problem. If I follow that link:

https://www.facebook.com/notes/977148692766914/

it gives another link:

https://www.facebook.com/whitehat/researcher-settings/

I click "Enable the Whitehat Settings menu for your Facebook account". Then I click "Facebook Lite for Android". Then I go here:

https://www.facebook.com/whitehat/researcher-settings/help/

Under "Enable setting from Facebook on Android", it says go to the "Bookmark menu". I don't know what that is, so I just click on the menu button on the top right corner. Then I click Settings, then Privacy. On the next screen, I don't see anything for Whitehat.

I think you should remove the Facebook Whitehat recommendation, unless someone actually knows how to get it working. Otherwise people might go on a wild goose chase.

**Comment by pimterry** [comment]
Yes, I don't know about the details, but the setting is still there in the Facebook settings page you linked and they do have an [active](https://www.facebook.com/whitehat/thanks/) bug bounty program, so it should definitely work.

If it's not working for you then that sounds like a Facebook bug or some missing step in the docs - you should report this to them so they can fix it and help you get set up.

I'm very open to PRs against that blog post if you have a better way to intercept the Facebook apps, but as far as I'm aware the settings they provide are the best/only option. It's the officially supported option intended for security researchers doing exactly this, so until there's an alternative I'm going to leave it as it is.

If the Facebook team do explicitly tell you that this is no longer supported though, or if they provide a link to better documentation that fixes your issue, feel free to open a PR to update the blog post.

**Comment by 89z** [comment]
I got it working. First click top right menu. Right after "Settings", should be an option "Whitehat settings".

I think I had this problem before, and the issue was that after you enable whitehat on an account, it doesn't actually show up until the next day.

**Comment by 89z** [comment]
I think I set everything correct, but I am still getting "Certifcate rejected" errors in HTTP Toolkit. I saw an option in the Facebook app for "Proxy for Platform API requests", but I don't know what to set it to. What is the port HTTP Toolkit uses?

**Comment by 89z** [comment]
I am giving up on this for now, as it seems that the Facebook Whitehat thing is all a lie. I am going to put my steps below, in case anyone is able to notice that I did something wrong. I tested with HTTP Toolkit and MITM Proxy.

## HTTP Toolkit

Install Facebook app. Go to Menu, Settings & Privacy, Whitehat Settings. Click "allow user installed certificates". FORCE STOP app. Start HTTP Toolkit. Start app. Notice that requests are not being captured, and Certificate rejected errors are occurring.

## MITM Proxy

Install user certificate. Turn off proxy. Install app. Go to Menu, Settings & Privacy, Whitehat Settings. Click "allow user installed certificates". FORCE STOP app. Turn on proxy. Start app. Notice that requests are not being captured. Go back to Whitehat Settings, and click "Proxy for Platform API requests". Enter 127.0.0.1:8080. FORCE STOP app. Start app. Notice that requests are not being captured.

**Comment by 89z** [comment]
I didn't know how to tell them, so I just did it like I was claiming a bug bounty, then I explained the situation. It really felt like my issue was going into a black hole, but I guess we will see. I don't even think I got a confirmation email.

**Comment by 89z** [comment]
I think I figured it out. It seems Facebook is using HTTP/3 just like YouTube. I didnt notice at first, because Firefox sucks:

https://bugzilla.mozilla.org/show_bug.cgi?id=1765631
