### ISSUE TITLE
OkHttp3 - java.lang.NullPointerException: interceptor l3.e@b68a57c returned null

### ISSUE THREAD

**Issue by ilyasKerbal** [httptoolkit/frida-android-unpinning#48]
Hello, I encountered this issue while playing with a React Native app.
```
FATAL EXCEPTION: um.z Dispatcher
Process: com.cvent.mobile.eventapp, PID: 29861
java.lang.NullPointerException: interceptor l3.e@b68a57c returned null
	at an.g.b(RealInterceptorChain.kt:291)
	at zm.a.a(ConnectInterceptor.kt:33)
	at an.g.b(RealInterceptorChain.kt:167)
	at xm.a.a(CacheInterceptor.kt:192)
	at an.g.b(RealInterceptorChain.kt:167)
	at an.a.a(BridgeInterceptor.kt:168)
	at an.g.b(RealInterceptorChain.kt:167)
	at an.j.a(RetryAndFollowUpInterceptor.kt:35)
	at an.g.b(RealInterceptorChain.kt:167)
	at zm.e.r(RealCall.kt:114)
	at zm.e$a.run(RealCall.kt:52)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1137)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:637)
	at java.lang.Thread.run(Thread.java:1012)


```

Command
```
frida -U -l frida-script.js -f com.cvent.mobile.eventapp  
```

Information about the app
**processName:** 'com.cvent.mobile.eventapp',
**type:** React Native (Hermes engine)

**Comment by pimterry** [comment]
Can you share the output from the Frida command too? There should be lots of details there which will let you know which patches were applied, and what they did (or failed to do).

**Comment by ilyasKerbal** [comment]
This is the class that caused the problem `CertificateTransparencyInterceptor`
The app uses **[Appmattus -  certificatetransparency](https://github.com/appmattus/certificatetransparency)** 

the method that returned null is  `mo184a`

```
package p234l3;

import com.appmattus.certificatetransparency.chaincleaner.CertificateChainCleanerFactory;
import java.security.cert.Certificate;
import java.util.List;
import java.util.Set;
import javax.net.ssl.SSLPeerUnverifiedException;
import javax.net.ssl.SSLSocket;
import javax.net.ssl.X509TrustManager;
import nl.C5900n;
import p039c3.CTLogger;
import p039c3.CTPolicy;
import p039c3.VerificationResult;
import p056d3.DiskCache;
import p080e3.DataSource;
import p257m3.Host;
import p272n3.LogListResult;
import p272n3.LogListService;
import p438um.Connection;
import p438um.Handshake;
import p438um.Interceptor;
import p438um.Response;
import p538yl.C8165q;

/* renamed from: l3.e */
/* loaded from: classes.dex */
public final class CertificateTransparencyInterceptor extends CertificateTransparencyBase implements Interceptor {

    /* renamed from: g */
    private final boolean f21641g;

    /* renamed from: h */
    private final CTLogger f21642h;

    /* JADX WARN: 'super' call moved to the top of the method (can break code semantics) */
    public CertificateTransparencyInterceptor(Set<Host> set, Set<Host> set2, CertificateChainCleanerFactory certificateChainCleanerFactory, X509TrustManager x509TrustManager, LogListService logListService, DataSource<LogListResult> dataSource, CTPolicy cTPolicy, DiskCache diskCache, boolean z, CTLogger cTLogger) {
        super(set, set2, certificateChainCleanerFactory, x509TrustManager, logListService, dataSource, cTPolicy, diskCache);
        C8165q.m609g(set, "includeHosts");
        C8165q.m609g(set2, "excludeHosts");
        this.f21641g = z;
        this.f21642h = cTLogger;
    }

    @Override // p438um.Interceptor
    /* renamed from: a */
    public Response mo184a(Interceptor.InterfaceC7199a interfaceC7199a) {
        List<Certificate> m10132g;
        VerificationResult c1366b;
        C8165q.m609g(interfaceC7199a, "chain");
        String m3668h = interfaceC7199a.mo3610v().m3953l().m3668h();
        Connection mo3612a = interfaceC7199a.mo3612a();
        if (mo3612a != null) {
            Handshake mo101a = mo3612a.mo101a();
            if (mo101a == null || (m10132g = mo101a.m3706d()) == null) {
                m10132g = C5900n.m10132g();
            }
            if (mo3612a.mo100b() instanceof SSLSocket) {
                c1366b = m12134g(m3668h, m10132g);
            } else {
                c1366b = new VerificationResult.AbstractC1364c.C1366b(m3668h);
            }
            CTLogger cTLogger = this.f21642h;
            if (cTLogger != null) {
                cTLogger.m29332a(m3668h, c1366b);
            }
            if ((c1366b instanceof VerificationResult.AbstractC1358b) && this.f21641g) {
                throw new SSLPeerUnverifiedException("Certificate transparency failed");
            }
            return interfaceC7199a.mo3611b(interfaceC7199a.mo3610v());
        }
        throw new IllegalStateException("No connection found. Verify interceptor is added using addNetworkInterceptor");
    }
}
```

**Comment by pimterry** [comment]
Ok, good work finding that! This original appmatus code for this method is [here](https://github.com/appmattus/certificatetransparency/blob/main/certificatetransparency/src/main/kotlin/com/appmattus/certificatetransparency/internal/verifier/CertificateTransparencyInterceptor.kt), and this script does actually have an existing appmatus patch that covers this case: https://github.com/httptoolkit/frida-android-unpinning/blob/4d477da8c58c353a0290ec4829a1de4ca1ca5ae5/frida-script.js#L506-L516

Of course that doesn't work as this is obfuscated, so it doesn't find the class or method by name.

That means you'll need to add your own patch for this, but it should be fairly easy - you just need to modify the standard appmatus patch to use the obfuscated class and method names from this app build.

Does that make sense?

In future I'd love to extend this script (the automated fallback patcher particularly, which is a bit hit & miss for cases like this) to more accurately handle known cases like this even when obfuscated. It's clearly a bit difficult but should be possible I think by looking for methods with certain shapes of return types & parameters - independent of their names - and calling the matching methods if they exist. PRs or any research towards that would be very welcome if you're interested.

**Comment by ilyasKerbal** [comment]
Thanks a lot, your suggestion helped solve the problem. I need to change the classes and also the function calls inside.
I replaced `a.proceed(a.request())` to `a.b(a.v())`
```
try {
            const appmatus_Activity = Java.use('l3.e');
            appmatus_Activity['a'].implementation = function (a) {
                console.log('  --> Bypassing Appmattus (Transparency)');
                return a.b(a.v());
            };
            console.log('[+] Appmattus (CertificateTransparencyInterceptor)');
        } catch (err) {
            console.log('[ ] Appmattus (CertificateTransparencyInterceptor)');
        }
```
Maybe we can add a notice/info to the README; something like "Obfuscated classes may require additional examination". 

I agree with you, it's tough to pinpoint the exact methods based on just the return type/shape and parameters. Maybe another approach is to build a utility that generates a script from the APK.

**Comment by pimterry** [comment]
Excellent! I'll close this, glad to hear that's working for you.

I'll keep working on obfuscation solutions. Generating a script by analysing the APK itself is definitely an interesting idea! I think there's some good routes through to handle this automatically eventually, watch this space.
